#!/bin/bash

set -e 
set -x

pushd `dirname $BASH_SOURCE`

args=()

if [[ "${BUILDKITE_PLUGIN_GITHUB_CHECKS_DEBUG:-false}" =~ (true|on|1) ]] ; then
  args+=("-v")
fi

if [[ -n "${BUILDKITE_PLUGIN_GITHUB_CHECKS_APP_ID:-}" ]] ; then
  args+=("--app_id" "${BUILDKITE_PLUGIN_GITHUB_CHECKS_APP_ID:-}" )
fi

if [[ -n "${BUILDKITE_PLUGIN_GITHUB_CHECKS_PRIVATE_KEY:-}" ]] ; then
  args+=("--private_key" "${BUILDKITE_PLUGIN_GITHUB_CHECKS_PRIVATE_KEY:-}" )
fi

ghapp "${args[@]}" $*
